name: ci-wapis-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: "postgres://prisma:prisma@127.0.0.1:15432/tests"
          file_name: .env.test

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn test
