name: deploy-wapis-workflow
on: [push]
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: "yarn"

      - name: Install yarn dependencies
        run: yarn install

      - name: Run build task
        run: yarn build

      - name: Make env file
        run: |
          echo 'DATABASE_URL="postgres://prisma:prisma@127.0.0.1:15432/tests"' > $GITHUB_WORKSPACE/dist/.env.test
          echo 'PORT="3333"' >> $GITHUB_WORKSPACE/dist/.env.test
          echo 'SECRET="bWluaGFGUkFTRXNlY3JldGHDiWVzc2E="' >> $GITHUB_WORKSPACE/dist/.env.test
          echo 'TEST="${{ secrets.REMOTE_HOST }}"' >> $GITHUB_WORKSPACE/dist/.env.test

      - name: Install yarn dependencies
        run: yarn --cwd $GITHUB_WORKSPACE/dist install

      - name: Deploy to Server Contabo
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: "-rlgoDzvc -i --delete"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "/home/${{ github.REPOSITORY }}"
          EXCLUDE: "/node_modules/"
          SCRIPT_AFTER: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/${{ github.REPOSITORY }}
            rm -rf node_modules
            yarn install
            pm2 restart ${{ github.REPOSITORY }}