name: deploy-wapis-workflow
on: [push]
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Make env file
        run: echo 'DATABASE_URL="postgres://prisma:prisma@127.0.0.1:15432/tests"' > ".env.test"
      - run: echo 'PORT="3333"' > ".env.test"
      - run: echo 'SECRET="bWluaGFGUkFTRXNlY3JldGHDiWVzc2E="' > ".env.test"
      - run: echo 'TEST="${{ secrets.REMOTE_HOST }}' > ".env.test"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: "yarn"

      - name: Install yarn dependencies
        run: yarn install

      - name: Run build task
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.workspace }}/dist/*